blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.http import HttpResponse
#1.import system logging
# import logging
# #2.create(get) logger
# logger = logging.getLogger('django')
#
# def log(request):
#     # 3.use logger to record info
#     logger.info('info')
#     return HttpResponse('test')

urlpatterns = [
    path('admin/', admin.site.urls),
    #The parameters of include: urlconf_module, app_name
    #urlconf_module: Content of sub-application
    #app_name: Name of sub-application
    path('',include(('users.urls', 'users'), namespace='users')),
    #path('', log),

    path('',include(('home.urls','home'),namespace='home')),

]

#The route of image access.
from django.conf import settings
from django.conf.urls.static import static
urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

blog/home/urls.py
from django.urls import path
from home.views import IndexView,DetailView
urlpatterns = [
    path('',IndexView.as_view(),name='index'),

    path('detail/',DetailView.as_view(),name='detail'),
]

blog/users/urls.py
#Perform view routing of users sub-applications
from django.urls import path
from users.views import RegisterView, ImageCodeView, LoginView, LogoutView, ForgetPasswordView, UserCenterView, WriteBlogView
urlpatterns = [
    #The first parameter of path: routing
    #The second parameter of path: view function name
    path('register/',RegisterView.as_view(), name='register'),

    #Image verification code routing
    path('imagecode/', ImageCodeView.as_view(), name='imagecode'),

    path('login/',LoginView.as_view(),name='login'),

    path('logout/', LogoutView.as_view(), name='logout'),

    path('forgetpassword/', ForgetPasswordView.as_view(), name='forgetpassword'),

    path('center/', UserCenterView.as_view(), name='center'),

    path('writeblog/',WriteBlogView.as_view(), name='writeblog'),
]

blog/templates/center.html
<!DOCTYPE html>

<html lang="en">

<head>

    <meta charset="utf-8">

    <title> Personal Information </title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">

    <script type="text/javascript" src="{% static 'js/vue-2.5.16.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/axios-0.18.0.min.js' %}"></script>
</head>

<body>
<div id="app">


<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">

        <div>
            <a class="navbar-brand" href="{% url 'home:index' %}">The Film Blog</a>
        </div>
    </div>

    <div class="navbar-collapse">
        <ul class="nav navbar-nav">

            <li class="nav-item dropdown" v-if="is_login">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" @click="show_menu_click">[[username]]</a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="display: block" v-show="show_menu">
                    <a class="dropdown-item" href="{% url 'users:writeblog' %}">Write Blog</a>
                    <a class="dropdown-item" href='{% url 'users:center' %}'>Personal Information</a>
                    <a class="dropdown-item" href='{% url 'users:logout' %}'>Log out</a>
                </div>
            </li>

            <li class="nav-item" v-else>
                <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
            </li>

        </ul>
    </div>
</nav>

<!--content-->
<div class="container" style="margin-bottom: 20px">
        <div class="row">
            <div class="col-12">
                <br>
                <form method="post" enctype="multipart/form-data">
                 {% csrf_token %}
                    <!-- username -->
                <div class="form-group col-md-4">
                    <label for="username">Username</label>
                    <input type="text" class="form-control" disabled="disabled" id="username" name="username" value="{{ username }}" >
                </div>
                <br> <div class="col-md-4">Avatar</div>
                    {% if avatar %}
                        <img src="{{ avatar }}" style="max-width: 20%;" class="col-md-4"><br>
                    {% else %}
                        <img src="{% static 'img/avatar.jpg' %}" style="max-width: 20%;" class="col-md-4"><br>
                    {% endif %}

                    <!-- avatar -->
                    <div class="form-group col-md-4">
                        <label for="avatar">Upload avatar</label>
                        <input type="file" class="form-control-file" name="avatar" id="avatar">
                    </div>

                    <!-- phone -->
{#                    <div class="form-group col-md-4">#}
{#                        <label for="phone">Phone number</label>#}
{#                        <input type="text" class="form-control" disabled="disabled" id="phone" name="phone" value="{{ mobile }}">#}
{#                    </div>#}
                    <!-- desc -->
                    <div class="form-group col-md-4">
                        <label for="desc">Introduction</label>

                        <textarea type="text" class="form-control" id="desc" name="desc" rows="12" >{{ user_desc }}</textarea>
                    </div>

                    <button type="submit" class="btn btn-primary" style="margin-left: 12px" >Submit</button>
                </form>
            </div>
        </div>
    </div>


<!-- Footer -->
<footer class="py-3 bg-dark" id="footer">
    <div class="container">
        <h5 class="m-0 text-center text-white">Copyright @ Yangjf</h5>
    </div>
</footer>
</div>
<!-- 引入js -->
<script type="text/javascript" src="{% static 'js/host.js' %}"></script>
<script type="text/javascript" src="{% static 'js/common.js' %}"></script>
<script type="text/javascript" src="{% static 'js/center.js' %}"></script>
</body>

</html>

blog/templates/detail.html
<!DOCTYPE html>

<html lang="en">

<head>
    
    <meta charset="utf-8">

    <title>Article details</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    
    <script src="{% static 'ckeditor/ckeditor/plugins/prism/lib/prism/prism_patched.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'prism/prism.css' %}">
    
    <link rel="stylesheet" href="{% static 'common/common.css' %}">
    <link rel="stylesheet" href="{% static 'common/jquery.pagination.css' %}">
    
    <script type="text/javascript" src="{% static 'js/vue-2.5.16.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/axios-0.18.0.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
</head>

<body>
<div id="app">

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        
        <div>
            <a class="navbar-brand" href="{% url 'home:index' %}">The Film Blog</a>
        </div>
        
        <div class="collapse navbar-collapse" id="navbarNav">
            <div>
                <ul class="nav navbar-nav">
                    {% for cat in categories %}
                        {% if cat.id == category.id %}
                            <li class="nav-item active">
                                <a class="nav-link mr-2" href="/?cat_id={{ cat.id }}">{{ cat.title }}</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link mr-2" href="/?cat_id={{ cat.id }}">{{ cat.title }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    
    <div class="navbar-collapse">
        <ul class="nav navbar-nav">

            
            <li class="nav-item dropdown" v-if="is_login">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" @click="show_menu_click">[[username]]</a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="display: block" v-show="show_menu">
                    <a class="dropdown-item" href="{% url 'users:writeblog' %}">Write Blog</a>
                    <a class="dropdown-item" href='{% url 'users:center' %}'>Personal Information</a>
                    <a class="dropdown-item" href='{% url 'users:logout' %}'>Log out</a>
                </div>
            </li>
            <li class="nav-item" v-else>
                <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
            </li>

        </ul>
    </div>
</nav>

<!-- content -->
<div class="container">
    <div class="row">
        
        <div class="col-9">
            
            <h1 class="mt-4 mb-4">{{ article.title }}</h1>
            <div class="alert alert-success"><div>Author: <span>{{ article.author.username }}</span></div><div>Views: {{ article.total_views }}</div></div>
            <div class="col-12" style="word-break: break-all;word-wrap: break-word;">
                <p><p>{{ article.content|safe }}</p></p>
            </div>
            <br>
            
            <hr>
            <br>
        <h5 class="row justify-content-center" v-show="!is_login"><p>Please <a href="{% url 'users:login' %}"> Log in </a> to comment</p>
            </h5>
            <br>
            <div>
                <form method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="id" value="{{ article.id }}">
                <div class="form-group"><label for="body"><strong>I also want to comment:</strong></label>
                    <div>

                        <div class="django-ckeditor-widget" data-field-id="id_body" style="display: inline-block;">
                            <textarea cols="40" id="id_body" name="content" rows="10" required data-processed="0" :data-config="data_config" data-external-plugin-resources="[]" data-id="id_body" data-type="ckeditortype">

                            </textarea>
                        </div>
                    </div>
                </div>
                    
                    <button type="submit" class="btn btn-primary ">Send</button>
                </form>
            </div>
            <br>
            <!--Show comments -->
            <h4>There are {{ total_count }} comments</h4>
            <div class="row">
                {% for comment in comments %}
                    <div class="col-12" >
                            <hr><p><strong style="color: pink"></strong></p>
                            <div>
                                <div><span><strong>{{ comment.user.username }}</strong></span>&nbsp;<span style="color: gray">{{ comment.created|date:'Y-m-d H:i' }}</span></div>
                                <br>
                                <p>{{ comment.content|safe }}</p>
                            </div>
                </div>
                {% endfor %}
                <div class="pagenation" style="text-align: center">
                    <div id="pagination" class="page"></div>
                </div>
            </div> 

        </div>

        <div class="col-3 mt-4" id="sidebar" class="sidebar">
            <div class="sidebar__inner">
                    <h4><strong>Recommend</strong></h4>
                    <hr>
                    {% for hot_article in hot_articles %}
                        <a href="{% url 'home:detail' %}?id={{ hot_article.id }}" style="color: black">{{ hot_article.title }}</a><br>
                    {% endfor %}
            </div>
        </div>
    </div>

</div>


<!-- Footer -->
<footer class="py-3 bg-dark" id="footer">
    <div class="container">
        <h5 class="m-0 text-center text-white">Copyright @ Yangjf</h5>
    </div>
</footer>
</div>

<!--ckeditor-->
<script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}" data-ckeditor-basepath="{% static 'ckeditor/ckeditor/' %}" id="ckeditor-init-script"></script>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>

<script type="text/javascript" src="{% static 'js/host.js' %}"></script>
<script type="text/javascript" src="{% static 'js/common.js' %}"></script>
<script type="text/javascript" src="{% static 'js/detail.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.pagination.min.js' %}"></script>
<script type="text/javascript">
    $(function () {
        $('#pagination').pagination({
            currentPage: {{ page_num }},
            totalPage: {{ total_page }},
            callback:function (current) {

                location.href = '/detail/?id={{ article.id }}&page_size={{ page_size }}&page_num='+current;
            }
        })
    });
</script>

</body>

</html>

blog/templates/forget_password.html
<!DOCTYPE html>

<html lang="en">

<head>

    <meta charset="utf-8">
    {% load staticfiles %}
    <title>Reset Password</title>

    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">

    <script type="text/javascript" src="{% static 'js/vue-2.5.16.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/axios-0.18.0.min.js' %}"></script>
</head>
<body>
<div id="app">

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">

        <div>
            <a class="navbar-brand" href="{% url 'home:index' %}">The Film Blog</a>
        </div>
    </div>

    <div class="navbar-collapse">
        <ul class="nav navbar-nav">
            <li class="nav-item" >
                <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
            </li>
        </ul>
    </div>
</nav>
<!--content-->
<div class="container" style="height: 600px;margin-top: 20px">
    <div class="row" >
        <div class="col-12">
            <div class="col-6">
                <form class="login" id="login_form" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label >Account</label>
                        <div class="col-lg-6">
                            <input type="text" name="username" placeholder="Please enter your account" autofocus="autofocus" required
                                   id="id_login" class="form-control" v-model="username"/>
                        </div>
                        <small class="form-text text-muted ml-1" v-show="username_error" >[[username_error_message]]</small>
                    </div>
                    <!--Password-->
                    <div class="form-group">
                        <label >New password</label>
                        <div class="col-lg-6">
                            <input type="password" name="password" placeholder="Please enter your new password" required  class="form-control" v-model="password" @blur="check_password"/>
                        </div>
                        <small class="form-text text-muted ml-1" v-show="password_error" >[[password_error_message]]</small>
                    </div>
                    <!--confirm password-->
                    <div class="form-group">
                        <label >Confirm password</label>
                        <div class="col-lg-6">
                            <input type="password" name="password2" placeholder="Please enter your new password" required  class="form-control" v-model="password2" @blur="check_password2"/>
                        </div>
                        <small class="form-text text-muted ml-1" v-show="password2_error" >[[password2_error_message]]</small>
                    </div>
                    
                    <div class="form-group">
                        <label >Verification code</label>
                        <div class="row" style="margin-right:-80px;margin-left:0px">
                            <div class="col-lg-6">
                                <input type="text" name="imgage_code" placeholder="Please enter the verification code" required  class="form-control" v-model="image_code" @blur="check_image_code"/>
                            </div>
                            <img :src="image_code_url" @click="generate_image_code" alt="" style="width: 110px;height: 40px;">
                            <small class="form-text text-muted ml-1" v-show="image_code_error" >[[image_code_error_message]]</small>
                        </div>
                    </div>
                    <button class="primaryAction btn btn-primary" type="submit" @click="on_submit" id="submit_login">Reset password</button>
                </form>
            </div>
        </div>
    </div>
</div>


<footer class="py-3 bg-dark" id="footer">
    <div class="container">
        <h5 class="m-0 text-center text-white">Copyright @ Yangjf</h5>
    </div>
</footer>
</div>

<script type="text/javascript" src="{% static 'js/host.js' %}"></script>
<script type="text/javascript" src="{% static 'js/common.js' %}"></script>
<script type="text/javascript" src="{% static 'js/forget_password.js' %}"></script>

</body>
</html>

blog/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf8mb4">
    <title>The Film Blog</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'md_css/monokai.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'common/common.css' %}">
    <link rel="stylesheet" href="{% static 'common/jquery.pagination.css' %}">
    <script type="text/javascript" src="{% static 'js/vue-2.5.16.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/axios-0.18.0.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
</head>

<body>
<div id="app">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

    <div class="container">
        <div>
            <a class="navbar-brand" href="{% url 'home:index' %}">The Film Blog</a>
        </div>
        
        <div class="collapse navbar-collapse">
            <div>
                <ul class="nav navbar-nav">
                    {% for cat in categories %}
                        {% if cat.id == category.id %}
                            <li class="nav-item active">
                                <a class="nav-link mr-2" href="/?cat_id={{ cat.id }}">{{ cat.title }}</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link mr-2" href="/?cat_id={{ cat.id }}">{{ cat.title }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    
    <div class="navbar-collapse">
            <ul class="nav navbar-nav">
                
                <li class="nav-item dropdown" v-if="is_login">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" @click="show_menu_click">[[username]]</a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="display: block" v-show="show_menu">
                        <a class="dropdown-item" href="{% url 'users:writeblog' %}">Write a blog</a>
                        <a class="dropdown-item" href='{% url 'users:center' %}'>Personal Information</a>
                        <a class="dropdown-item" href='{% url 'users:logout' %}'>Log out</a>
                    </div>
                </li>
                <li class="nav-item" v-else>
                    <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
                </li>
            </ul>
        </div>
</nav>


<div class="container">
    {% for article in articles %}
        <div class="row mt-2">
            <div class="col-3">
                <img src="{{ article.avatar.url }}" alt="avatar" style="border-radius: 20px; max-width: 100%">
            </div>
            <div class="col">
                <a  role="button" href="/?cat_id={{ article.category.id }}" class="btn btn-sm mb-2 btn-warning">{{ article.category.title }}</a>
                <h4>
                    <b><a href="{% url 'home:detail' %}?id={{ article.id }}" style="color: black;">{{ article.title }}</a></b>
                </h4>
                <p>
                    <span><i class="fas fa-eye" style="color: lightskyblue;"></i>{{ article.total_views }}</span>
                    <span><i class="fas fa-comments" style="color: yellowgreen;"></i>{{ article.comments_count }}</span>
                    <span><i class="fas fa-clock" style="color: pink;"></i>{{ article.created|date }}</span>
                </p>
            </div>
            <hr style="width: 100%;"/>
    </div>
    {% endfor %}


    <div class="pagenation" style="text-align: center">
        <div id="pagination" class="page"></div>
    </div>
</div>

<!-- Footer -->
<footer class="py-3 bg-dark" id="footer">
    <div class="container">
        <h5 class="m-0 text-center text-white">Copyright @ Yangjf</h5>
    </div>
</footer>
</div>


<script type="text/javascript" src="{% static 'js/host.js' %}"></script>
<script type="text/javascript" src="{% static 'js/common.js' %}"></script>
<script type="text/javascript" src="{% static 'js/index.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.pagination.min.js' %}"></script>
<script type="text/javascript">
    $(function () {
        $('#pagination').pagination({
            currentPage: {{ page_num }},
            totalPage: {{ total_page }},
            callback:function (current) {

                location.href = '/?cat_id={{ category.id}}&page_size={{ page_size }}&page_num='+current;
            }
        })
    });
</script>
</body>
</html>

blog/templates/login.html
<!DOCTYPE html>

<html lang="en">

<head>

    <meta charset="utf-8">

    <title>Log in</title>
    {% load staticfiles %}

    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">


    <script type="text/javascript" src="{% static 'js/vue-2.5.16.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/axios-0.18.0.min.js' %}"></script>
</head>

<body>
<div id="app">


<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">

        <div>
            <a class="navbar-brand" href="{% url 'home:index' %}">The Film Blog</a>
        </div>
    </div>
    <div class="navbar-collapse">
    </div>
</nav>
<!--content-->
<div class="container" style="height: 600px;margin-top: 20px">
    <div class="row" >
        <div class="col-12">
            <div class="col-6">
                <form class="login" id="login_form" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_login">Username</label>
                        <input type="text" name="username" placeholder="Please enter your username" autofocus="autofocus" required id="id_login" class="form-control" v-model="username" @blur="check_username"/>
                        <small class="form-text text-muted ml-1">No account yet? <a href="{% url 'users:register' %}" style="color: cornflowerblue; ">Register a new account</a>
                        </small>
                    </div>
                    <div class="form-group mb-1">
                        <label for="id_password">Password:</label>
                        <input type="password" name="password" placeholder="Please enter your password" required id="id_password" class="form-control" v-model="password" @blur="check_password"/>
                        <small class="form-text text-muted ml-1"><a class="secondaryAction layui-text" href="{% url 'users:forgetpassword' %}">Forgot password?</a>
                        </small>
                    </div>
                    <div class="custom-control custom-checkbox mb-2">
                        <input type="checkbox" name="remember" id="id_remember" checked class="custom-control-input" v-model="remembered"/>
                        <label for="id_remember" class="custom-control-label">Remember me</label>
                    </div>
                    <button class="primaryAction btn btn-primary" type="submit" id="submit_login" @click="on_submit">Login</button>
                </form>
            </div>
        </div>
    </div>
</div>

    
<!-- Footer -->
<footer class="py-3 bg-dark" id="footer">
    <div class="container">
        <h5 class="m-0 text-center text-white">Copyright @ Yangjf</h5>
    </div>
</footer>

</div>

<script type="text/javascript" src="{% static 'js/host.js' %}"></script>
<script type="text/javascript" src="{% static 'js/common.js' %}"></script>
<script type="text/javascript" src="{% static 'js/login.js' %}"></script>
</body>

</html>

blog/templates/write_blog.html
<!DOCTYPE html>

<html lang="en">

<head>
    
    <meta charset="utf-8">
    
    <title> Write Blog </title>
    {% load staticfiles %}
    
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    
    <link rel="stylesheet" href="{% static 'md_css/monokai.css'%}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    
    <script type="text/javascript" src="{% static 'js/vue-2.5.16.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/axios-0.18.0.min.js' %}"></script>
</head>

<body>
<div id="app">

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        
        <div>
            <a class="navbar-brand" href="{% url 'home:index' %}">The Film Blog</a>
        </div>
    </div>
    
    <div class="navbar-collapse">
        <ul class="nav navbar-nav">
            
            <li class="nav-item dropdown" v-if="is_login">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" @click="show_menu_click">[[username]]</a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="display: block" v-show="show_menu">
                    <a class="dropdown-item" href="{% url 'users:writeblog' %}">Write Blog</a>
                    <a class="dropdown-item" href='{% url 'users:center' %}'>Personal Information</a>
                    <a class="dropdown-item" href='{% url 'users:logout' %}'>Log out</a>
                </div>
            </li>
            
            <li class="nav-item" v-else>
                <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
            </li>
        </ul>
    </div>
</nav>


<div class="container" style="margin-bottom: 20px">
    <div class="row">
        <div class="col-12">
            <br>
            
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label for="avatar">Image</label>
                    <input type="file" class="form-control-file" name="avatar" id="avatar" >
                </div>

                
                <div class="form-group">
                    
                    <label for="title">Title</label>
                    
                    <input type="text" class="form-control" id="title" name="title">
                </div>
                
                
                <div class="form-group">
                    <label for="category">Category</label>
                    <select class="form-control col-3" id="category" name="category">
                        {% for category in categories %}
                            <option value="{{ category.id }}">{{ category.title }}</option>
                        {% endfor %}
                    </select>
                </div>
                
                <div class="form-group">
                    <label for="body">Body</label>
                    
                    <textarea lang="en" cols="40" id="id_body" name="content" rows="10" required data-processed="0" :data-config="data_config" data-external-plugin-resources="[]" data-id="id_body" data-type="ckeditortype">
                        </textarea>
                </div>
                
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>


<footer class="py-3 bg-dark" id="footer">
    <div class="container">
        <h5 class="m-0 text-center text-white">Copyright @ Yangjf</h5>
    </div>
</footer>
</div>


<script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}" data-ckeditor-basepath="{% static 'ckeditor/ckeditor/' %}" id="ckeditor-init-script"></script>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>


<script type="text/javascript" src="{% static 'js/host.js' %}"></script>
<script type="text/javascript" src="{% static 'js/common.js' %}"></script>
<script type="text/javascript" src="{% static 'js/write_blog.js' %}"></script>
</body>

</html>